### PR TITLE
Fix/amqp connection

### LINKED ISSUE #19: [BUG] AMQP Virtual host with extra slash character "/"
https://github.com/kestra-io/plugin-amqp/blob/3da6f792e65c665b4bd71932e40eb9029e90aca2/src/main/java/io/kestra/plugin/amqp/AbstractAmqpConnection.java#L40

The way you extract the virtual host from the AMQP connection URI is adding an extra slash character to the virtual hostname. 

For instance, if I have this connection URI: "**amqp://user:pass@rabbitmq.host.info:5672/test**", your code is getting as virtual hostname "**/test**" because you are using the method "[getPath()](https://www.geeksforgeeks.org/uri-getpath-method-in-java-with-examples/)" of URI class which returns the leading slash as explained in the documentation link. 

Please, update the code to remove the extra slash character.

### PR DESCRIPTION
**Pull request by loicmathieu**
@jaime-amesti-frontiers  I took your commit and open a new PR from a new branch as you used the master branch so I cannot add commits on it.

This will fix #19 by providing individual properties for each connection properties.

### CODE REVIEW

**Review by tchiotludo — APPROVED** [review]

**Comment by loicmathieu** [comment]
@jaime-amesti-frontiers thanks for your contribution, this is now merged. The new version of the plugin will allow configuring the AMQP production with multiple properties solivng the issue.

**Comment by jaime-amesti-frontiers** [comment]
Thank you very much @loicmathieu .

**Comment by loicmathieu** [comment]
@jaime-amesti-frontiers I trigger a new build of Kestra, if you use our `develop` or `develop-full` docker images you can try it.

**Comment by jaime-amesti-frontiers** [comment]
I've just tested it, and it works fine. The only thing I saw is the documentation does not reflect your latest changes, probably because it displays the last release documentation, right?
tempsnip2

**Comment by loicmathieu** [comment]
@jaime-amesti-frontiers great to know it works!
The documentation is cached in the browser (for one day I think) so it will reflect the latest change later.

**Comment by tchiotludo** [comment]
if you want to force the destiny : 
image

**Pull request merged**
