### PR TITLE
Removed leading slash character from virtual host name

### PR DESCRIPTION
**Pull request by jaime-amesti-frontiers**
Hi, I think this small change could fix the issue #19

### CODE REVIEW

**Comment by loicmathieu** [comment]
Thanks, this change makes our test fail with:

`com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=530, reply-text=NOT_ALLOWED - vhost my_vhost not found, class-id=10, method-id=40)`

It seems at least with our test on the version of RabitMQ we use the vhost must start with /.

Maybe you can give us more context on your issue so we may understand what's going on ?

**Comment by jaime-amesti-frontiers** [comment]
Any update??

**Comment by loicmathieu** [comment]
@jaime-amesti-frontiers the issue is that if we change this, it will be a breaking change that other users may be impacted by. This is shown by our current test that has a legitimate task configuration now fail.

I'll discuss with the team as if we do the change the vhost can no longer start with a `/` which is a legitimate vhost name for RabbitMQ. We may need to provide more control over RabbitMQ connection configuration to workaround this.

**Comment by jaime-amesti-frontiers** [comment]
Hi @loicmathieu , 
Honestly, I write more code in C# than in Java, so I prefer you take care of it.
Thanks for managing it.

**Comment by loicmathieu** [comment]
OK great, working on it

**Comment by jaime-amesti-frontiers** [comment]
Can I cancel this PR?

**Comment by loicmathieu** [comment]
Closed in favor of https://github.com/kestra-io/plugin-amqp/pull/21

**Pull request closed without merging**
